# Generated by Django 5.2.7 on 2025-10-13 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome Ingrediente')),
                ('unit', models.CharField(max_length=50, verbose_name='Unità di Misura (es: g, ml, pezzi)')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nome Ricetta')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MON', 'Lunedì'), ('TUE', 'Martedì'), ('WED', 'Mercoledì'), ('THU', 'Giovedì'), ('FRI', 'Venerdì'), ('SAT', 'Sabato'), ('SUN', 'Domenica')], max_length=3, verbose_name='Giorno')),
                ('meal_type', models.CharField(choices=[('LUN', 'Pranzo'), ('DIN', 'Cena'), ('BRK', 'Colazione'), ('SNK', 'Snack')], max_length=3, verbose_name='Tipo Pasto')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.recipe', verbose_name='Ricetta Scelta')),
            ],
            options={
                'verbose_name': 'Pianificazione Settimanale',
                'verbose_name_plural': 'Pianificazioni Settimanali',
                'ordering': ['day_of_week', 'meal_type'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Quantità')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ingredient', verbose_name='Ingrediente')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_list', to='core.recipe', verbose_name='Ricetta')),
            ],
            options={
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
    ]
