# Generated by Django 5.2.7 on 2025-10-19 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Lunedì'), ('TUE', 'Martedì'), ('WED', 'Mercoledì'), ('THU', 'Giovedì'), ('FRI', 'Venerdì'), ('SAT', 'Sabato'), ('SUN', 'Domenica')], max_length=3, verbose_name='Giorno')),
                ('meal_type', models.CharField(choices=[('LUN', 'Pranzo'), ('DIN', 'Cena'), ('BRK', 'Colazione'), ('SNK', 'Snack')], max_length=3, verbose_name='Tipo Pasto')),
            ],
            options={
                'verbose_name': 'Slot Pasto',
                'verbose_name_plural': 'Slot Pasti',
                'ordering': ['day', 'meal_type'],
                'unique_together': {('day', 'meal_type')},
            },
        ),
        migrations.CreateModel(
            name='MealRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.recipe', verbose_name='Ricetta Scelta')),
                ('meal_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='core.mealslot', verbose_name='Slot Pasto')),
            ],
            options={
                'verbose_name': 'Ricetta nel Pasto',
                'verbose_name_plural': 'Ricette nel Pasto',
                'ordering': ['meal_slot', 'id'],
                'unique_together': {('meal_slot', 'recipe')},
            },
        ),
        migrations.DeleteModel(
            name='WeeklyPlan',
        ),
    ]
